[book]
authors = ["ChihChengLiang", "Yahsin Huang"]
language = "en"
multilingual = false
src = "src"
title = "Untitled Ethereum book"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["statics/mermaid.min.js", "statics/mermaid-init.js"]
